---
enable_secret: "cisco"
console_password: "cisco"

banner_login: |
  ****************************************
  *  UNAUTHORIZED ACCESS IS PROHIBITED  *
  *    Authorized users only!           *
  ****************************************

vlans:
  - id: 20
    name: "Internet_access"
  - id: 30
    name: "Dnipro_access"

access_ports:
  - interface: "GigabitEthernet0/2"
    vlan: 20
  - interface: "GigabitEthernet0/3"
    vlan: 20
  - interface: "GigabitEthernet1/0"
    vlan: 30
  - interface: "GigabitEthernet1/1"
    vlan: 30

trunk_port: "GigabitEthernet0/1"
trunk_allowed_vlans: [10, 20, 30]
